remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Leonardo Emili
description: Former MSc CS student <a href="https://www.uniroma1.it/en/" target=”_blank”>@Sapienza</a>. Former intern <a href="https://www.linkedin.com/company/apple/" target=”_blank”>@Apple</a>. Natural Language Processing and Deep Learning enthusiast.
show_downloads: false
logo: https://github.com/LeonardoEmili.png?size=256
github: [metadata]
color-scheme: auto
